### ISSUE TITLE
Lesson 1: Using Issues to Communicate

### ISSUE THREAD

**Issue by 1point618** [1point618/exemplar-prototype-1#1]
Hi @PeterBell! Welcome to the team.

I'm Brienne, your new manager. Today I'll be onboarding you to GitHub. GitHub is where we manage our projects and store our code and content. You'll be up and running in no time.

This is an issue, which we use to communicate about the project on GitHub. To get started, type a comment below. @-mention me by typing the `@` symbol followed by my user name so I get pinged when you do.

**Comment by PeterBell** [comment]
Hey @1point618 sounds good!

**Comment by 1point618** [comment]
Great job! @-mentions are used to tag people into converations so that they know you're talking about them and want their input. A person will receive a notification when you @-mention them.

Now, on the right, assign this issue to yourself and label it with the gold `learning` label. I'll keep track of your progress in this comment. If you're not sure if you did it right, just check here to see if I checked the box or not.
- [x] Assign self.
- [x] Add `learning` label.

**Comment by 1point618** [comment]
Great job @PeterBell!

We use issues for all sorts of communications, including reporting bugs, requestiong new features, open-ended discussions about our site, and tracking the development of the site. An issue can be assigned to someone so that they know that they "own" the issue and the work that it will take to complete it. We label issues so that we can more easily search through them. You can also use [markdown](https://help.github.com/articles/markdown-basics/) to format issues—that's how I made those sweet check boxes and that link. 

There's one more thing to learn about Issues, then we can move on. Close this issue below, then click on the "Issues" icon to the right, then go to the other issues named **Lesson 2: Managing Issues**.
