### ISSUE TITLE
Fix the Readme File

### ISSUE THREAD

**Issue by 1point618** [1point618/exemplar-prototype-1#3]
The readme.md file is a file that sits in the main directory of a repo. It's another way we use to communicate with each other. The readme.md file should include everything we need to get the repo running on our local computers. 

I've included the text we want in the readme below. Add the text, commit it to a new branch (**this is very important!**), then submit a pull request for the changes.
## Progress
- [x] Edit readme file w/ correct stuff.
- [x] Commit the file to a new branch called "readme-bugfix".
- [x] Create a pull request, include the text `fixes #3`.
- [x] Once they comment w/ a :+1:, merge the PR.
- [x] Delete the branch.

Once you've finished this lesson, I'll create a new `learning` issue and assign it to you, you'll need to go there to learn more.

If you need help, just @-mention me below asking for help and I'll send you a more detailed tutorial for how to do this.

**Comment by 1point618** [comment]
```
# Readme

This is the content of the readme file.

It should be markdown.

* Expose the students to markdown.
* They'll learn what it is later.
```

**Comment by PeterBell** [comment]
Hey @1point618 I'm not sure how to edit the readme file

**Comment by 1point618** [comment]
Sure thing @PeterBell! I wanted to push you because you'd learned the rest so quickly, but this tricks everyone up the first time they try it. What you need to do is follow the instructions below.
1. Click on the repo name.
2. Click on the readme.md file.
3. Click on the edit button (it's a pencil).
4. Copy and paste the above text into the edit screen.
5. Add a commit title and message, or just use the default ones.
6. Click on the "create a new branch" button.
7. Name the branch `readme-bugfix`.
8. Propose the file change. This will take you to a new PR screen.
9. In the comment section of the PR, include the text `fixes #3`. This tells the PR that it is associated with this issue.
10. Create the pull request.
11. Wiat for the teacher to comment on your PR. 
12. Once they've given you the thumbs up, click "merge the pull request", and confirm the merge.
13. Delete the branch.
14. Come back to this issue. It should be closed, because of the `fixes` tag.

Once you do, I'll tell you a bit more about _why_ we do things this way. It's called the GitHub Workflow and it's a pretty important part of how we work.

**Comment by PeterBell** [comment]
http://pbell.wistia.com/medias/gmg4goyobr?embedType=iframe&videoFoam=true&videoWidth=640

**Comment by PeterBell** [comment]
<script charset="ISO-8859-1" src="//fast.wistia.com/assets/external/E-v1.js" async></script><div class="wistia_embed wistia_async_gmg4goyobr popover=true popoverAnimateThumbnail=true" style="display:inline-block;height:84px;width:150px">&nbsp;</div>

**Comment by PeterBell** [comment]
<script charset="ISO-8859-1" src="//fast.wistia.com/assets/external/E-v1.js" async></script><div class="wistia_responsive_padding" style="padding:56.25% 0 0 0;position:relative;"><div class="wistia_responsive_wrapper" style="height:100%;left:0;position:absolute;top:0;width:100%;"><div class="wistia_embed wistia_async_gmg4goyobr videoFoam=true" style="height:100%;width:100%">&nbsp;</div></div></div>

**Comment by PeterBell** [comment]
<script src="http://vjs.zencdn.net/4.0/video.js"></script>

<video id="pelican-installation" class="video-js vjs-default-skin" controls
preload="auto" width="683" height="384" poster="/static/screencasts/pelican-installation.png"
data-setup="{}">
<source src="/static/screencasts/pelican-installation.mp4" type='video/mp4'>
</video>

**Comment by PeterBell** [comment]
<script src="http://vjs.zencdn.net/4.0/video.js"></script>

<video id="pelican-installation" class="video-js vjs-default-skin" controls preload="auto" width="683" height="384" poster="/static/screencasts/pelican-installation.png" data-setup="{}">
<source src="/static/screencasts/pelican-installation.mp4" type='video/mp4'>
</video>
